# This file was generated by GoReleaser. DO NOT EDIT.
cask "forthwith" do
  name "forthwith"
  desc "Forthwith CLI - manage your Forthwith resources from the command line"
  homepage "https://github.com/forthwith-dev/forthwith-cli"
  version "0.1.0-rc.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "forthwith"

  on_macos do
    on_intel do
      url "https://github.com/forthwith-dev/forthwith-releases/releases/download/v#{version}/forthwith_#{version}_darwin_amd64.tar.gz"
      sha256 "cea4560083d99f8fd9ee66b08d793a6b6810a78c15ce2b75295233a455ec4bd8"
    end
    on_arm do
      url "https://github.com/forthwith-dev/forthwith-releases/releases/download/v#{version}/forthwith_#{version}_darwin_arm64.tar.gz"
      sha256 "e560e250c6f269a8ef58db6658d8f68685c03ee3b6a0b35b732ec423aadc77d5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/forthwith-dev/forthwith-releases/releases/download/v#{version}/forthwith_#{version}_linux_amd64.tar.gz"
      sha256 "e8d6abe3c9bb00d1c3d904987b3a1bf37e695687b1c658086d0143a6bdd2154a"
    end
    on_arm do
      url "https://github.com/forthwith-dev/forthwith-releases/releases/download/v#{version}/forthwith_#{version}_linux_arm64.tar.gz"
      sha256 "d562acc95f6350780c0b293cf5fe150872ecc11a7c46d79ab8f29c76646ffa3d"
    end
  end

  # No zap stanza required
end
